[project]
name = "BOWDN"
description = "BOWDN makes it easy to define commands that can be run from string inputs."
version = "1.0.0"
authors = [
    { name = "Alex Kumpula", email = "" }
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]